[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false
# log_level = "error"

[tasks.run]
command = "cargo"
args = ["run", "--features", "dev"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.build-dev]
command = "cargo"
args = ["build", "--features", "dev"]

[tasks.watch]
command = "cargo"
args = ["run", "--features", "dev"]
watch = { delay = 10.0, watch = ["./src", "./assets"] }

#wasm tasks

[tasks.run-wasm]
command = "cargo"
args = ["run", "--target", "wasm32-unknown-unknown", "--profile", "wasm-dev"]
dependencies = ["install-wasm"]

[tasks.watch-wasm]
command = "cargo"
args = ["run", "--target", "wasm32-unknown-unknown", "--profile", "wasm-dev"]
dependencies = ["install-wasm"]
watch = { delay = 10.0, watch = ["./src", "./assets"] }

[tasks.run-wasm-release]
command = "cargo"
args = ["run", "--target", "wasm32-unknown-unknown", "--profile", "wasm-release"]
dependencies = ["install-wasm"]

[tasks.install-wasm]
# install_crate = { crate_name = "wasm-server-runner", bin = "wasm-server-runner"}
command = "rustup"
args = ["target", "install", "wasm32-unknown-unknown"]
dependencies = ["install-wasm-server-runner"]

[tasks.install-wasm-server-runner]
command = "cargo"
args = ["install", "--path", "./crates/wasm-server-runner"]

#action related tasks

[tasks.actions]
run_task = [
    { name = "fmt" },
    { name = "check" },
    { name = "clippy" },
    { name = "test-suite" },
]

[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.check]
command = "cargo"
args = ["check", "--features", "dev"]

[tasks.test]
command = "cargo"
args = ["test", "--features", "dev"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--features", "dev"]

#test suite 

[tasks.test-suite]
dependencies = ["test"]

#member tasks

[tasks.member-actions]
workspace = true
run_task = [
    { name = "fmt", fork = true },
    { name = "member-clippy", fork = true },
    { name = "member-check", fork = true },
    { name = "member-test", fork = true },
]

[tasks.member-clippy]
command = "cargo"
args = ["clippy"]

[tasks.member-check]
command = "cargo"
args = ["check"]

[tasks.member-test]
command = "cargo"
args = ["test"]

#workspace tasks

[tasks.all-actions]
run_task = [
    { name = "member-actions" },
    { name = "actions" },
]