name: Continuous Integration

on: [push]

jobs:
  simple:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - flags: --target wasm32-unknown-unknown --profile wasm-release
            os: ubuntu-latest
            rustup: wasm32-unknown-unknown
          - rustup: stable --profile minimal
          - flags: --features dev

        # actions: ["clippy"]

    name: Continuous Integrtion on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      # When rustup is updated, it tries to replace its binary, which on Windows is somehow locked.
      # This can result in the CI failure, see: https://github.com/rust-lang/rustup/issues/3029
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install ${{ matrix.rustup }}
          rustup component add clippy rustfmt
      - name: install other dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo fmt --all
          cargo check ${{ matrix.flags }}
          cargo clippy ${{ matrix.flags }}
          cargo test ${{ matrix.flags }}